# Generated by Django 5.0.7 on 2024-07-28 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='query',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_term',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
