# Generated by Django 5.0.7 on 2024-07-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_searchhistory_query_searchhistory_search_term_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
