# Generated by Django 5.0.7 on 2024-07-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_reviewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_term',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_url',
            field=models.URLField(max_length=600),
        ),
    ]
