# Generated by Django 5.0.7 on 2024-07-22 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_reading', models.CharField(max_length=100)),
                ('first_name_sorting', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_sorting', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_reading', models.CharField(max_length=256)),
                ('title_sorting', models.CharField(blank=True, max_length=256, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True)),
                ('sub_title_reading', models.CharField(blank=True, max_length=256, null=True)),
                ('original_title', models.CharField(blank=True, max_length=256, null=True)),
                ('classification_number', models.CharField(blank=True, max_length=50, null=True)),
                ('character_usage', models.CharField(max_length=50)),
                ('copyright_flag', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('book_card_url', models.URLField()),
                ('role_flag', models.CharField(default='著者', max_length=50)),
                ('text_file_url', models.URLField(blank=True, null=True)),
                ('html_file_url', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='reviews.author')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_works', to='reviews.author')),
            ],
            options={
                'unique_together': {('title', 'sub_title')},
            },
        ),
    ]
