# Generated by Django 4.1 on 2024-07-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("person_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("first_name_reading", models.CharField(max_length=100)),
                ("last_name_reading", models.CharField(max_length=100)),
                ("first_name_sorting", models.CharField(max_length=100)),
                ("last_name_sorting", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
