# Generated by Django 5.0.7 on 2024-07-23 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_info', models.CharField(max_length=6000)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_publication', to='reviews.work')),
            ],
        ),
    ]
