# Generated by Django 4.1 on 2024-07-21 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("title_reading", models.CharField(max_length=256)),
                ("title_sorting", models.CharField(max_length=256)),
                ("sub_title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "sub_title_reading",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "first_published",
                    models.CharField(blank=True, max_length=245, null=True),
                ),
                (
                    "classification_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("character_usage", models.CharField(max_length=50)),
                ("copyright_flag", models.BooleanField(default=False)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("last_updated", models.DateField(blank=True, null=True)),
                ("book_card_url", models.URLField()),
                ("text_file_url", models.URLField()),
                ("html_file_url", models.URLField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="reviews.author",
                    ),
                ),
                (
                    "translator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translated_works",
                        to="reviews.author",
                    ),
                ),
            ],
            options={
                "unique_together": {("title", "sub_title")},
            },
        ),
        migrations.CreateModel(
            name="WorkEditInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inputter", models.CharField(blank=True, max_length=255, null=True)),
                ("proofer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "base_text_name1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "base_text_publisher1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "base_text_first_published_year1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "base_text_name2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "base_text_publisher2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "base_text_first_published_year2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "original_base_text_name1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "original_base_text_publisher1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "original_base_text_first_published_year1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "original_base_text_name2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "original_base_text_publisher2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "original_base_text_first_published_year2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("creation_date", models.DateField(blank=True, null=True)),
                ("modified_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "work",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.work"
                    ),
                ),
            ],
        ),
    ]
