# Generated by Django 5.0.7 on 2024-07-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_firstpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpublication',
            name='publication_info',
            field=models.TextField(),
        ),
    ]
