# Generated by Django 4.1 on 2024-07-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_work_workeditinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='html_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='text_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
