# Generated by Django 5.0.7 on 2024-07-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_firstpublication_publication_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='author',
        ),
        migrations.RemoveField(
            model_name='work',
            name='translator',
        ),
        migrations.AddField(
            model_name='work',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='works', to='reviews.author'),
        ),
        migrations.AddField(
            model_name='work',
            name='translator',
            field=models.ManyToManyField(blank=True, related_name='translated_works', to='reviews.author'),
        ),
    ]
