# Generated by Django 4.1 on 2024-07-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_work_html_file_url_alter_work_text_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='first_published',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
