# Generated by Django 4.1 on 2024-07-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_work_first_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_birth_date_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='is_death_date_partial',
            field=models.BooleanField(default=False),
        ),
    ]
