# Generated by Django 5.0.7 on 2024-07-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_work_author_remove_work_translator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='translator',
            new_name='translators',
        ),
    ]
