# Generated by Django 4.1 on 2024-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_author_is_birth_date_partial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='first_published',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='workeditinfo',
            name='base_text_first_published_year1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workeditinfo',
            name='base_text_first_published_year2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workeditinfo',
            name='original_base_text_first_published_year1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workeditinfo',
            name='original_base_text_first_published_year2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
