# Generated by Django 5.0.7 on 2024-07-23 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_author_work_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='translators',
        ),
        migrations.AddField(
            model_name='work',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_works', to='reviews.author'),
        ),
        migrations.AddField(
            model_name='work',
            name='other_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_role_works', to='reviews.author'),
        ),
        migrations.AddField(
            model_name='work',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_works', to='reviews.author'),
        ),
    ]
