# Generated by Django 5.0.7 on 2024-07-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_work_translators_work_editor_work_other_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='full_name_reading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
