# Generated by Django 4.1 on 2024-07-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_work_first_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='first_published',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
