# Generated by Django 5.0.7 on 2024-07-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_author_full_name_author_full_name_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDC_Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(max_length=10, unique=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='reviews.ndc_classification')),
            ],
        ),
    ]
