# Generated by Django 4.1 on 2024-07-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_work_first_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_birth_date_partial',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_death_date_partial',
        ),
    ]
