# Generated by Django 5.0.7 on 2024-07-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_ndc_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndc_classification',
            name='genre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
