# Generated by Django 4.1 on 2024-07-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_work_first_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='first_published',
        ),
    ]
