# Generated by Django 5.0.7 on 2024-07-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_ndc_classification_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndc_classification',
            name='parent',
        ),
        migrations.AlterField(
            model_name='ndc_classification',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
