# Generated by Django 5.0.7 on 2024-07-24 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_ndc_classification_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='genre_info1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_works', to='reviews.ndc_classification'),
        ),
        migrations.AddField(
            model_name='work',
            name='genre_info2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_works', to='reviews.ndc_classification'),
        ),
    ]
