# Generated by Django 5.0.7 on 2024-07-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_work_genre_info1_work_genre_info2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndc_classification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='reviews.ndc_classification'),
        ),
    ]
