# Generated by Django 5.0.7 on 2024-07-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_remove_ndc_classification_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=set(),
        ),
    ]
