# Generated by Django 5.0.7 on 2024-07-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_work_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTextInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_text_name', models.CharField(max_length=500)),
                ('base_text_publisher', models.CharField(blank=True, max_length=256, null=True)),
                ('base_text_publish_year', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_text_name', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_text_publisher', models.CharField(blank=True, max_length=256, null=True)),
                ('parent_text_publish_year', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('title', 'sub_title', 'original_title', 'book_card_url')},
        ),
        migrations.AddField(
            model_name='work',
            name='base_text_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_text_info', to='reviews.basetextinfo'),
        ),
    ]
