# Generated by Django 5.0.7 on 2024-07-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_review_is_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
