# Generated by Django 5.0.7 on 2024-07-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_review_profile_alter_review_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
